using System;
using System.Collections.Generic;

#nullable disable

namespace APCore.Models
{
    public partial class FlightInformation
    {
        public int Id { get; set; }
        public int? TypeId { get; set; }
        public int? RegisterId { get; set; }
        public int? FlightTypeId { get; set; }
        public int? FlightStatusId { get; set; }
        public int? AirlineOperatorsId { get; set; }
        public int? FlightGroupId { get; set; }
        public string FlightNumber { get; set; }
        public int? FromAirportId { get; set; }
        public int? ToAirportId { get; set; }
        public DateTime? Std { get; set; }
        public DateTime? Sta { get; set; }
        public DateTime? ChocksOut { get; set; }
        public DateTime? Takeoff { get; set; }
        public DateTime? Landing { get; set; }
        public DateTime? ChocksIn { get; set; }
        public int? FlightH { get; set; }
        public byte? FlightM { get; set; }
        public int? BlockH { get; set; }
        public byte? BlockM { get; set; }
        public decimal? Gwto { get; set; }
        public decimal? Gwland { get; set; }
        public decimal? FuelPlanned { get; set; }
        public decimal? FuelActual { get; set; }
        public decimal? FuelDeparture { get; set; }
        public decimal? FuelArrival { get; set; }
        public int? PaxAdult { get; set; }
        public int? PaxInfant { get; set; }
        public int? PaxChild { get; set; }
        public int? CargoWeight { get; set; }
        public int? CargoUnitId { get; set; }
        public int? BaggageCount { get; set; }
        public int? CustomerId { get; set; }
        public int? FlightPlanId { get; set; }
        public DateTime? DateCreate { get; set; }
        public int? CargoCount { get; set; }
        public int? BaggageWeight { get; set; }
        public int? FuelUnitId { get; set; }
        public string ArrivalRemark { get; set; }
        public string DepartureRemark { get; set; }
        public int? EstimatedDelay { get; set; }
        public int? FlightStatusUserId { get; set; }
        public int? CancelReasonId { get; set; }
        public string CancelRemark { get; set; }
        public DateTime? CancelDate { get; set; }
        public int? OtoAirportId { get; set; }
        public DateTime? Osta { get; set; }
        public string OtoAirportIata { get; set; }
        public int? RedirectReasonId { get; set; }
        public string RedirectRemark { get; set; }
        public DateTime? RedirectDate { get; set; }
        public bool? IsApplied { get; set; }
        public DateTime? DateApplied { get; set; }
        public int? FlightPlanRegisterId { get; set; }
        public int? CalendarId { get; set; }
        public int? BoxId { get; set; }
        public int? RampReasonId { get; set; }
        public string RampRemark { get; set; }
        public DateTime? RampDate { get; set; }
        public int? FpflightHh { get; set; }
        public int? FpflightMm { get; set; }
        public decimal? Fpfuel { get; set; }
        public decimal? Defuel { get; set; }
        public bool? SplitDuty { get; set; }
        public decimal? UsedFuel { get; set; }
        public int? Jlblhh { get; set; }
        public int? Jlblmm { get; set; }
        public int? Pflr { get; set; }
        public int? CpcrewId { get; set; }
        public string Cpregister { get; set; }
        public int? CppositionId { get; set; }
        public int? CpflightTypeId { get; set; }
        public int? CpfdpitemId { get; set; }
        public bool? Cpdh { get; set; }
        public int? Cpfdpid { get; set; }
        public string Cpinstructor { get; set; }
        public string Cpp1 { get; set; }
        public string Cpp2 { get; set; }
        public string Cpsccm { get; set; }
        public string Cpisccm { get; set; }
        public int? NightTime { get; set; }
        public DateTime? JloffBlock { get; set; }
        public DateTime? JlonBlock { get; set; }
        public DateTime? JltakeOff { get; set; }
        public DateTime? Jllanding { get; set; }
        public int? NotifiedDelay { get; set; }
        public DateTime? FlightDate { get; set; }
        public string Updnote { get; set; }
        public Guid? Guid { get; set; }
        public int? JluserId { get; set; }
        public int? JlapproverId { get; set; }
        public DateTime? Jldate { get; set; }
        public DateTime? JldateApproved { get; set; }
        public string Jlno { get; set; }
        public string SerialNo { get; set; }
        public string Ltr { get; set; }
        public decimal? RvsmGndCpt { get; set; }
        public decimal? RvsmGndStby { get; set; }
        public decimal? RvsmGndFo { get; set; }
        public decimal? RvsmFltCpt { get; set; }
        public decimal? RvsmFltStby { get; set; }
        public decimal? RvsmFltFo { get; set; }
        public decimal? Cargo { get; set; }
        public decimal? FuelDensity { get; set; }
        public string CommanderNote { get; set; }
        public bool? AttAsr { get; set; }
        public bool? AttVoyageReport { get; set; }
        public bool? AttRepositioning1 { get; set; }
        public bool? AttRepositioning2 { get; set; }
        public int? Version { get; set; }
        public bool? IsSynced { get; set; }
        public string Pf { get; set; }
        public string Pic { get; set; }
        public int? Picid { get; set; }
        public string Sic { get; set; }
        public int? Sicid { get; set; }
        public DateTime? JldatePicapproved { get; set; }
        public string JlsignedBy { get; set; }
        public string Alt1 { get; set; }
        public string Alt2 { get; set; }
        public string Alt3 { get; set; }
        public string Alt4 { get; set; }
        public string Alt5 { get; set; }
        public int? Utcdiff { get; set; }
        public decimal? FptripFuel { get; set; }
    }
}
