using System;
using System.Collections.Generic;

#nullable disable

namespace APCore.Models
{
    public partial class ViewBoxCrew
    {
        public int Id { get; set; }
        public int BoxId { get; set; }
        public int PositionId { get; set; }
        public int EmployeeId { get; set; }
        public int? AvailabilityId { get; set; }
        public string Remark { get; set; }
        public DateTime? ReportingTime { get; set; }
        public string Position { get; set; }
        public string Pid { get; set; }
        public int PersonId { get; set; }
        public DateTime? DateJoinCompany { get; set; }
        public int? ExpCompany { get; set; }
        public int? CustomerId { get; set; }
        public int? GroupId { get; set; }
        public string JobGroupCode { get; set; }
        public string JobGroup { get; set; }
        public int MarriageId { get; set; }
        public string ImageUrl { get; set; }
        public string Nid { get; set; }
        public int SexId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public DateTime? DateBirth { get; set; }
        public string Email { get; set; }
        public string Phone1 { get; set; }
        public string Mobile { get; set; }
        public string FaxTelNumber { get; set; }
        public string PassportNumber { get; set; }
        public DateTime? DatePassportIssue { get; set; }
        public DateTime? DatePassportExpire { get; set; }
        public string Address { get; set; }
        public DateTime? DateJoinAvation { get; set; }
        public int? Exp { get; set; }
        public DateTime? DateLastCheckUp { get; set; }
        public DateTime? DateNextCheckUp { get; set; }
        public DateTime? DateYearOfExperience { get; set; }
        public string CaoCardNumber { get; set; }
        public DateTime? DateCaoCardIssue { get; set; }
        public string CompetencyNo { get; set; }
        public int? CaoInterval { get; set; }
        public DateTime? DateCaoCardExpire { get; set; }
        public int IsMedicalExpired { get; set; }
        public string Pplnumber { get; set; }
        public DateTime? PpldateIssue { get; set; }
        public DateTime? PpldateExpire { get; set; }
        public int? PplexpireStatus { get; set; }
        public string Cplnumber { get; set; }
        public DateTime? CpldateIssue { get; set; }
        public DateTime? CpldateExpire { get; set; }
        public int? CplexpireStatus { get; set; }
        public string Atplnumber { get; set; }
        public DateTime? AtpldateIssue { get; set; }
        public DateTime? AtpldateExpire { get; set; }
        public int? AtplexpireStatus { get; set; }
        public string Mccnumber { get; set; }
        public DateTime? MccdateIssue { get; set; }
        public DateTime? MccdateExpire { get; set; }
        public int? MccexpireStatus { get; set; }
        public int? CurrentLocationAirportId { get; set; }
        public string CurrentLocationAirporIata { get; set; }
        public int IsAvSecExpired { get; set; }
        public int IsCcrmexpired { get; set; }
        public int IsCmcexpired { get; set; }
        public int IsColdWeatherExpired { get; set; }
        public int IsCrmexpired { get; set; }
        public int IsDgexpired { get; set; }
        public int IsHotWeatherExpired { get; set; }
        public int IsLicenceExpired { get; set; }
        public int IsLicenceIrexpired { get; set; }
        public int IsLprexpired { get; set; }
        public int IsFirstAidExpired { get; set; }
        public int? RemainFirstAid { get; set; }
        public int IsPassportExpired { get; set; }
        public int IsProficiencyExpired { get; set; }
        public int IsSeptexpired { get; set; }
        public int IsSeptpexpired { get; set; }
        public int IsSmsexpired { get; set; }
        public int IsUpsetRecoveryTrainingExpired { get; set; }
        public int? RemainAvSec { get; set; }
        public int? RemainCao { get; set; }
        public int? RemainCcrm { get; set; }
        public int? RemainCmc { get; set; }
        public int? RemainColdWeather { get; set; }
        public int? RemainCrm { get; set; }
        public int? RemainDg { get; set; }
        public int? RemainHotWeather { get; set; }
        public int? RemainLicence { get; set; }
        public int? RemainLicenceIr { get; set; }
        public int? RemainLpr { get; set; }
        public int? RemainMedical { get; set; }
        public int? RemainPassport { get; set; }
        public int? RemainProficiency { get; set; }
        public int? RemainSept { get; set; }
        public int? RemainSeptp { get; set; }
        public int? RemainSms { get; set; }
        public int? RemainUpsetRecoveryTraining { get; set; }
        public string ScheduleName { get; set; }
        public string Code { get; set; }
        public DateTime? Std { get; set; }
        public DateTime? Sta { get; set; }
        public int? FromAirportId { get; set; }
        public int? ToAirportId { get; set; }
        public int? Duty { get; set; }
        public int? Flight { get; set; }
        public DateTime? RestUntil { get; set; }
        public DateTime? RestFrom { get; set; }
        public DateTime? DefaultStart { get; set; }
        public DateTime? DefaultEnd { get; set; }
    }
}
