using System;
using System.Collections.Generic;

#nullable disable

namespace APCore.Models
{
    public partial class ViewTolndcard
    {
        public int Id { get; set; }
        public int FlightId { get; set; }
        public string Information { get; set; }
        public string Rw { get; set; }
        public string Tl { get; set; }
        public string Fe { get; set; }
        public string Wind { get; set; }
        public string Visibility { get; set; }
        public string Cloud { get; set; }
        public string Temp { get; set; }
        public string Qnh { get; set; }
        public string DewP { get; set; }
        public string Wxcondition { get; set; }
        public string Star { get; set; }
        public string App { get; set; }
        public string Mas { get; set; }
        public string ActLandingWeight { get; set; }
        public string Flap { get; set; }
        public string StabTrim { get; set; }
        public string Verf { get; set; }
        public string FuelToAlternate { get; set; }
        public string Ta { get; set; }
        public string Zfw { get; set; }
        public string Tofuel { get; set; }
        public string Toweight { get; set; }
        public string Cg { get; set; }
        public string V1 { get; set; }
        public string Vr { get; set; }
        public string V2 { get; set; }
        public string Type { get; set; }
        public string Lda { get; set; }
        public string JlsignedBy { get; set; }
        public DateTime? JldatePicapproved { get; set; }
        public string DateUpdate { get; set; }
        public string User { get; set; }
        public DateTime? BlockOn { get; set; }
        public DateTime? Landing { get; set; }
        public DateTime? TakeOff { get; set; }
        public DateTime? BlockOff { get; set; }
        public DateTime? BlockOnLocal { get; set; }
        public DateTime? LandingLocal { get; set; }
        public DateTime? TakeOffLocal { get; set; }
        public DateTime? BlockOffLocal { get; set; }
        public DateTime? Std { get; set; }
        public DateTime? Sta { get; set; }
        public DateTime? Stdlocal { get; set; }
        public DateTime? Stalocal { get; set; }
        public int? FlightStatusId { get; set; }
        public int? RegisterId { get; set; }
        public int? FlightTypeId { get; set; }
        public string AircraftType { get; set; }
        public int? TypeId { get; set; }
        public string FlightNumber { get; set; }
        public int? FromAirport { get; set; }
        public int? ToAirport { get; set; }
        public int? CustomerId { get; set; }
        public string FromAirportIata { get; set; }
        public string ToAirportIata { get; set; }
        public string Register { get; set; }
        public int Msn { get; set; }
        public string FlightStatus { get; set; }
        public string ArrivalRemark { get; set; }
        public string DepartureRemark { get; set; }
        public DateTime? Stdday { get; set; }
        public DateTime? Staday { get; set; }
        public DateTime? StddayLocal { get; set; }
        public DateTime? StadayLocal { get; set; }
        public int? DelayBlockOff { get; set; }
        public int? DelayTakeoff { get; set; }
        public DateTime? Departure { get; set; }
        public DateTime? Arrival { get; set; }
        public DateTime? DepartureLocal { get; set; }
        public DateTime? ArrivalLocal { get; set; }
        public int? BlockTime { get; set; }
        public int? FlightTime { get; set; }
        public int? ScheduledFlightTime { get; set; }
        public int? FpflightTime { get; set; }
        public int? Pflr { get; set; }
        public int? PaxChild { get; set; }
        public int? PaxInfant { get; set; }
        public int? PaxAdult { get; set; }
        public int? PaxTotal { get; set; }
        public int? PaxRevenued { get; set; }
        public int? FuelUnitId { get; set; }
        public decimal? FuelRemaining { get; set; }
        public decimal? FuelUplift { get; set; }
        public decimal? FuelUsed { get; set; }
        public decimal? FuelTotal { get; set; }
        public int? TotalSeat { get; set; }
        public int BaggageWeight { get; set; }
        public int CargoWeight { get; set; }
        public int? Freight { get; set; }
        public DateTime? FlightDate { get; set; }
        public int? CargoCount { get; set; }
        public int? BaggageCount { get; set; }
        public decimal? Fpfuel { get; set; }
        public int? CpcrewId { get; set; }
        public string Cpregister { get; set; }
        public int? CppositionId { get; set; }
        public int? CpflightTypeId { get; set; }
        public int? CpfdpitemId { get; set; }
        public bool? Cpdh { get; set; }
        public int? Cpfdpid { get; set; }
        public string Cpp1 { get; set; }
        public string Cpinstructor { get; set; }
        public string Cpp2 { get; set; }
        public string Cpsccm { get; set; }
        public string Cpisccm { get; set; }
        public int NightTime { get; set; }
        public int? DayTime { get; set; }
        public int? JluserId { get; set; }
        public int? JlapproverId { get; set; }
        public DateTime? Jldate { get; set; }
        public DateTime? JldateApproved { get; set; }
        public string Jlno { get; set; }
        public string SerialNo { get; set; }
        public decimal? RvsmGndCpt { get; set; }
        public string Ltr { get; set; }
        public decimal? RvsmGndStby { get; set; }
        public decimal? RvsmGndFo { get; set; }
        public decimal? RvsmFltCpt { get; set; }
        public decimal? RvsmFltStby { get; set; }
        public decimal? RvsmFltFo { get; set; }
        public decimal? Cargo { get; set; }
        public decimal? FuelDensity { get; set; }
        public string CommanderNote { get; set; }
        public bool? AttAsr { get; set; }
        public bool? AttVoyageReport { get; set; }
        public bool? AttRepositioning1 { get; set; }
        public bool? AttRepositioning2 { get; set; }
        public string Jluser { get; set; }
        public string Jlapprover { get; set; }
        public int IsJl { get; set; }
        public int IsJlapproved { get; set; }
        public string Pf { get; set; }
        public string Ipname { get; set; }
        public int? Ipid { get; set; }
        public string IpscheduleName { get; set; }
        public string P1name { get; set; }
        public int? P1id { get; set; }
        public string P1scheduleName { get; set; }
        public string P2name { get; set; }
        public int? P2id { get; set; }
        public string P2scheduleName { get; set; }
        public string Pic { get; set; }
        public int? Picid { get; set; }
        public string Sic { get; set; }
        public int? Sicid { get; set; }
    }
}
