using System;
using System.Collections.Generic;

#nullable disable

namespace APCore.Models
{
    public partial class ViewRosterSheet
    {
        public int Id { get; set; }
        public DateTime? Stdday { get; set; }
        public string Register { get; set; }
        public string FlightNumber { get; set; }
        public string FromAirportIata { get; set; }
        public string ToAirportIata { get; set; }
        public int? FromAirport { get; set; }
        public int? ToAirport { get; set; }
        public string Route { get; set; }
        public string Fstdlocal { get; set; }
        public string Fstalocal { get; set; }
        public string Fstd { get; set; }
        public string Fsta { get; set; }
        public DateTime? Std { get; set; }
        public DateTime? Sta { get; set; }
        public DateTime? Stdlocal { get; set; }
        public DateTime? Stalocal { get; set; }
        public string Duration { get; set; }
        public int? DurationMinutes { get; set; }
        public string FlightStatus { get; set; }
        public int? FlightStatusId { get; set; }
        public int IsCanceled { get; set; }
        public DateTime? Departure { get; set; }
        public DateTime? DepartureLocal { get; set; }
        public DateTime? Arrival { get; set; }
        public DateTime? ArrivalLocal { get; set; }
        public int? FlightTimeActual { get; set; }
        public int? BlockTime { get; set; }
        public int? Ip1 { get; set; }
        public string Ip1name { get; set; }
        public bool? Ip1dh { get; set; }
        public int? Ip2 { get; set; }
        public string Ip2name { get; set; }
        public bool? Ip2dh { get; set; }
        public int? P11 { get; set; }
        public string P11name { get; set; }
        public bool? P11dh { get; set; }
        public int? P12 { get; set; }
        public string P12name { get; set; }
        public bool? P12dh { get; set; }
        public int? P13 { get; set; }
        public string P13name { get; set; }
        public bool? P13dh { get; set; }
        public int? P14 { get; set; }
        public string P14name { get; set; }
        public bool? P14dh { get; set; }
        public int? P15 { get; set; }
        public string P15name { get; set; }
        public bool? P15dh { get; set; }
        public int? P21 { get; set; }
        public string P21name { get; set; }
        public bool? P21dh { get; set; }
        public int? P22 { get; set; }
        public string P22name { get; set; }
        public bool? P22dh { get; set; }
        public int? P23 { get; set; }
        public string P23name { get; set; }
        public bool? P23dh { get; set; }
        public int? P24 { get; set; }
        public string P24name { get; set; }
        public bool? P24dh { get; set; }
        public int? P25 { get; set; }
        public string P25name { get; set; }
        public bool? P25dh { get; set; }
        public int? Safety1 { get; set; }
        public string Safety1Name { get; set; }
        public bool? Safety1Dh { get; set; }
        public int? Safety2 { get; set; }
        public string Safety2Name { get; set; }
        public bool? Safety2Dh { get; set; }
        public int? Isccm1 { get; set; }
        public string Isccm1name { get; set; }
        public bool? Isccm1dh { get; set; }
        public int? Sccm1 { get; set; }
        public string Sccm1name { get; set; }
        public bool? Sccm1dh { get; set; }
        public int? Sccm2 { get; set; }
        public string Sccm2name { get; set; }
        public bool? Sccm2dh { get; set; }
        public int? Sccm3 { get; set; }
        public int? Sccm4 { get; set; }
        public int? Sccm5 { get; set; }
        public string Sccm3name { get; set; }
        public string Sccm4name { get; set; }
        public string Sccm5name { get; set; }
        public bool? Sccm3dh { get; set; }
        public bool? Sccm4dh { get; set; }
        public bool? Sccm5dh { get; set; }
        public int? Ccm1 { get; set; }
        public string Ccm1name { get; set; }
        public bool? Ccm1dh { get; set; }
        public int? Ccm2 { get; set; }
        public string Ccm2name { get; set; }
        public bool? Ccm2dh { get; set; }
        public int? Ccm3 { get; set; }
        public string Ccm3name { get; set; }
        public bool? Ccm3dh { get; set; }
        public int? Ccm4 { get; set; }
        public string Ccm4name { get; set; }
        public bool? Ccm4dh { get; set; }
        public int? Ccm5 { get; set; }
        public string Ccm5name { get; set; }
        public bool? Ccm5dh { get; set; }
        public int? Obs1 { get; set; }
        public string Obs1name { get; set; }
        public bool? Obs1dh { get; set; }
        public int? Obs2 { get; set; }
        public string Obs2name { get; set; }
        public bool? Obs2dh { get; set; }
        public int? Check1 { get; set; }
        public string Check1name { get; set; }
        public bool? Check1dh { get; set; }
        public int? Check2 { get; set; }
        public string Check2name { get; set; }
        public bool? Check2dh { get; set; }
        public int? FlightTime { get; set; }
        public string DeadHeads { get; set; }
        public string Color1 { get; set; }
        public string Color2 { get; set; }
    }
}
