using System;
using System.Collections.Generic;

#nullable disable

namespace APCore.Models
{
    public partial class ViewEmployee
    {
        public int Id { get; set; }
        public string Pid { get; set; }
        public int? BaseAirportId { get; set; }
        public string BaseAirport { get; set; }
        public int? CurrentLocationAirport { get; set; }
        public string CurrentLocationCity { get; set; }
        public int CurrentLocationCityId { get; set; }
        public DateTime? DateJoinCompany { get; set; }
        public int ExpCompany { get; set; }
        public bool IsActive { get; set; }
        public DateTime? DateRegister { get; set; }
        public DateTime? DateConfirmed { get; set; }
        public bool IsDeleted { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int? CustomerId { get; set; }
        public int? GroupId { get; set; }
        public int? C1groupId { get; set; }
        public string JobGroupC1 { get; set; }
        public string JobGroupCodeC1 { get; set; }
        public int? C2groupId { get; set; }
        public string JobGroupC2 { get; set; }
        public string JobGroupCodeC2 { get; set; }
        public int? C3groupId { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public string JobGroupRoot { get; set; }
        public int MarriageId { get; set; }
        public string Nid { get; set; }
        public int SexId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public DateTime? DateBirth { get; set; }
        public string Email { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Mobile { get; set; }
        public string FaxTelNumber { get; set; }
        public string PassportNumber { get; set; }
        public DateTime? DatePassportIssue { get; set; }
        public DateTime? DatePassportExpire { get; set; }
        public string Address { get; set; }
        public DateTime? DateJoinAvation { get; set; }
        public int Exp { get; set; }
        public DateTime? DateLastCheckUp { get; set; }
        public DateTime? DateNextCheckUp { get; set; }
        public DateTime? DateYearOfExperience { get; set; }
        public string CaoCardNumber { get; set; }
        public DateTime? DateCaoCardIssue { get; set; }
        public DateTime? DateCaoCardExpire { get; set; }
        public string CompetencyNo { get; set; }
        public int? CaoInterval { get; set; }
        public int? CaoIntervalCalanderTypeId { get; set; }
        public string Remark { get; set; }
        public string StampNumber { get; set; }
        public string StampUrl { get; set; }
        public string TechLogNo { get; set; }
        public DateTime? DateIssueNdt { get; set; }
        public int? IntervalNdt { get; set; }
        public string Ndtnumber { get; set; }
        public int? NdtintervalCalanderTypeId { get; set; }
        public string Nickname { get; set; }
        public int? CityId { get; set; }
        public string FatherName { get; set; }
        public string Idno { get; set; }
        public string UserId { get; set; }
        public string ImageUrl { get; set; }
        public int? CustomerCreatorId { get; set; }
        public int Age { get; set; }
        public int LocationId { get; set; }
        public int? OrgRoleId { get; set; }
        public string LocationPhone { get; set; }
        public bool IsMainLocation { get; set; }
        public string MaritalStatus { get; set; }
        public string Sex { get; set; }
        public string CaoIntervalCalanderType { get; set; }
        public string NdtintervalCalanderType { get; set; }
        public string City { get; set; }
        public int StateId { get; set; }
        public string State { get; set; }
        public int CountryId { get; set; }
        public string Country { get; set; }
        public string CityFullName { get; set; }
        public string Customer { get; set; }
        public string Location { get; set; }
        public int? RootLocation { get; set; }
        public string LocationCode { get; set; }
        public int PersonId { get; set; }
        public int EmployeeLocationId { get; set; }
        public string Post { get; set; }
        public int? RemainNdt { get; set; }
        public int? RemainCao { get; set; }
        public int? RemainPassport { get; set; }
        public int IsNdtexpired { get; set; }
        public int IsNdtexpiring { get; set; }
        public int IsCaoexpired { get; set; }
        public int IsCaoexpiring { get; set; }
        public int IsMedicalExpiring { get; set; }
        public int IsPassportExpired { get; set; }
        public int IsPassportExpiring { get; set; }
        public DateTime? DateExpireNdt { get; set; }
        public string Types { get; set; }
        public int BookAlert { get; set; }
        public int CriticalCertificatesCount { get; set; }
        public DateTime? ProficiencyExpireDate { get; set; }
        public DateTime? CrewMemberCertificateExpireDate { get; set; }
        public DateTime? LicenceExpireDate { get; set; }
        public DateTime? LicenceIrexpireDate { get; set; }
        public DateTime? SimulatorLastCheck { get; set; }
        public DateTime? SimulatorNextCheck { get; set; }
        public string RampPassNo { get; set; }
        public DateTime? RampPassExpireDate { get; set; }
        public DateTime? LanguageCourseExpireDate { get; set; }
        public string LicenceTitle { get; set; }
        public DateTime? LicenceInitialIssue { get; set; }
        public string RaitingCertificates { get; set; }
        public DateTime? LicenceIssueDate { get; set; }
        public string LicenceDescription { get; set; }
        public int? ProficiencyCheckType { get; set; }
        public DateTime? ProficiencyCheckDate { get; set; }
        public DateTime? ProficiencyValidUntil { get; set; }
        public string ProficiencyDescriptionOpc { get; set; }
        public DateTime? ProficiencyCheckDateOpc { get; set; }
        public DateTime? ProficiencyValidUntilOpc { get; set; }
        public DateTime? DateTriexpired { get; set; }
        public DateTime? DateTreexpired { get; set; }
        public int? Icaolprlevel { get; set; }
        public DateTime? IcaolprvalidUntil { get; set; }
        public int? MedicalClass { get; set; }
        public string PostalCode { get; set; }
        public string MedicalLimitation { get; set; }
        public string ProficiencyDescription { get; set; }
        public DateTime? VisaExpireDate { get; set; }
        public DateTime? SeptissueDate { get; set; }
        public DateTime? SeptexpireDate { get; set; }
        public DateTime? SeptpissueDate { get; set; }
        public DateTime? SeptpexpireDate { get; set; }
        public DateTime? DangerousGoodsIssueDate { get; set; }
        public DateTime? DangerousGoodsExpireDate { get; set; }
        public DateTime? CcrmissueDate { get; set; }
        public DateTime? CcrmexpireDate { get; set; }
        public DateTime? CrmissueDate { get; set; }
        public DateTime? CrmexpireDate { get; set; }
        public DateTime? SmsissueDate { get; set; }
        public DateTime? SmsexpireDate { get; set; }
        public DateTime? AviationSecurityIssueDate { get; set; }
        public DateTime? AviationSecurityExpireDate { get; set; }
        public DateTime? EgpwsissueDate { get; set; }
        public DateTime? EgpwsexpireDate { get; set; }
        public DateTime? UpsetRecoveryTrainingIssueDate { get; set; }
        public DateTime? UpsetRecoveryTrainingExpireDate { get; set; }
        public DateTime? ColdWeatherOperationIssueDate { get; set; }
        public DateTime? HotWeatherOperationIssueDate { get; set; }
        public DateTime? ColdWeatherOperationExpireDate { get; set; }
        public DateTime? HotWeatherOperationExpireDate { get; set; }
        public DateTime? FirstAidIssueDate { get; set; }
        public DateTime? FirstAidExpireDate { get; set; }
        public DateTime? PbnrnavissueDate { get; set; }
        public DateTime? PbnrnavexpireDate { get; set; }
        public int? RemainFirstAid { get; set; }
        public int IsFirstAidExpired { get; set; }
        public int? RemainCmc { get; set; }
        public int IsCmcexpired { get; set; }
        public int? RemainLicence { get; set; }
        public int IsLicenceExpired { get; set; }
        public int? RemainLicenceIr { get; set; }
        public int IsLicenceIrexpired { get; set; }
        public int? RemainProficiency { get; set; }
        public int IsProficiencyExpired { get; set; }
        public int? RemainProficiencyOpc { get; set; }
        public int IsProficiencyOpcexpired { get; set; }
        public int? RemainLpr { get; set; }
        public int IsLprexpired { get; set; }
        public int? RemainMedical { get; set; }
        public int IsMedicalExpired { get; set; }
        public int? RemainSept { get; set; }
        public int IsSeptexpired { get; set; }
        public int? RemainSeptp { get; set; }
        public int IsSeptpexpired { get; set; }
        public int? RemainDg { get; set; }
        public int IsDgexpired { get; set; }
        public int? RemainCrm { get; set; }
        public int IsCrmexpired { get; set; }
        public int? RemainCcrm { get; set; }
        public int IsCcrmexpired { get; set; }
        public int? RemainSms { get; set; }
        public int IsSmsexpired { get; set; }
        public int? RemainAvSec { get; set; }
        public int IsAvSecExpired { get; set; }
        public int? RemainUpsetRecoveryTraining { get; set; }
        public int IsUpsetRecoveryTrainingExpired { get; set; }
        public int? RemainColdWeather { get; set; }
        public int IsColdWeatherExpired { get; set; }
        public int? RemainHotWeather { get; set; }
        public int IsHotWeatherExpired { get; set; }
        public string ScheduleName { get; set; }
        public string Code { get; set; }
        public DateTime DateInactiveBegin { get; set; }
        public DateTime DateInactiveEnd { get; set; }
        public string LinkedIn { get; set; }
        public string Telegram { get; set; }
        public string WhatsApp { get; set; }
        public int? AircraftTypeId { get; set; }
        public DateTime? DateTypeIssue { get; set; }
        public DateTime? DateTypeExpire { get; set; }
        public int? TypeRemain { get; set; }
        public DateTime? LineIssueDate { get; set; }
        public DateTime? LineExpireDate { get; set; }
        public DateTime? RecurrentIssueDate { get; set; }
        public DateTime? RecurrentExpireDate { get; set; }
        public int IsRecurrentExpired { get; set; }
        public int IsLineExpired { get; set; }
        public int IsTriexpired { get; set; }
        public int IsTreexpired { get; set; }
        public int? RemainTri { get; set; }
        public int? RemainTre { get; set; }
        public int? RemainRecurrent { get; set; }
        public int? RemainLine { get; set; }
        public int? RemainEgpws { get; set; }
        public int? RemainRsp { get; set; }
        public int? RemainLrc { get; set; }
        public double FlightSum { get; set; }
        public int FlightEarly { get; set; }
        public int FlightLate { get; set; }
        public bool? InActive { get; set; }
        public string JobGroupMain { get; set; }
        public string JobGroupMainCode { get; set; }
        public string JobGroupCode2 { get; set; }
        public string CodeX { get; set; }
        public int? RemainTypeMd { get; set; }
        public int? RemainType737 { get; set; }
        public int? RemainTypeAirbus { get; set; }
        public int? RemainHf { get; set; }
        public int? RemainAsd { get; set; }
        public int? RemainGom { get; set; }
        public int? RemainAsf { get; set; }
        public int? RemainCc { get; set; }
        public int? RemainErp { get; set; }
        public int? RemainMb { get; set; }
        public int? RemainPs { get; set; }
        public int? RemainAnnex { get; set; }
        public int? RemainDrm { get; set; }
        public int? RemainFmtd { get; set; }
        public int? RemainMel { get; set; }
        public int? RemainMet { get; set; }
        public int? RemainPer { get; set; }
        public int? RemainLpcc1 { get; set; }
        public int? RemainLpcc2 { get; set; }
        public int? RemainLpcc3 { get; set; }
        public int? RemainLineC1 { get; set; }
        public int? RemainLineC2 { get; set; }
        public int? RemainLineC3 { get; set; }
        public int? RemainRamp { get; set; }
        public int? RemainAc { get; set; }
        public int? RemainUprt { get; set; }
        public int? RemainSfi { get; set; }
        public int? RemainSfe { get; set; }
        public int? RemainTri2 { get; set; }
        public int? RemainTre2 { get; set; }
        public int? RemainIri { get; set; }
        public int? RemainIre { get; set; }
        public int? RemainCri { get; set; }
        public int? RemainCre { get; set; }
        public int? RemainSfi2 { get; set; }
        public int? RemainSfe2 { get; set; }
        public int? RemainAirCrew { get; set; }
        public int? RemainAirOps { get; set; }
        public int? RemainSop { get; set; }
        public int? RemainDiff31 { get; set; }
        public int? RemainDiff34 { get; set; }
        public int? RemainOma1 { get; set; }
        public int? RemainOmb1 { get; set; }
        public int? RemainOmc1 { get; set; }
        public int? RemainOma2 { get; set; }
        public int? RemainOmb2 { get; set; }
        public int? RemainOmc2 { get; set; }
        public int? RemainOma3 { get; set; }
        public int? RemainOmb3 { get; set; }
        public int? RemainOmc3 { get; set; }
        public int? RemainMap { get; set; }
        public int? RemainComRes { get; set; }
        public int? RemainOpcc1 { get; set; }
        public int? RemainOpcc2 { get; set; }
        public int? RemainOpcc3 { get; set; }
    }
}
